from selenium import webdriver
from time import sleep
from selenium.webdriver.chrome.options import Options
#options = Options()
#options.add_argument('--headless')
#driver = webdriver.Chrome('C:/Python39/chromedriver',options=options)
driver = webdriver.Chrome('chromedriver')
sleep(3)
driver.get('https://www.mizuhobank.co.jp/retail/takarakuji/check/loto/loto6/index.html')
sleep(3)
lot6 = ['LOT6']
lot6.append(driver.find_elements_by_xpath('//th')[1].text)
lot6.append(driver.find_elements_by_xpath('//td')[0].text)
lot6.append(driver.find_elements_by_xpath('//td')[1].text)
lot6.append(driver.find_elements_by_xpath('//td')[2].text)
lot6.append(driver.find_elements_by_xpath('//td')[3].text)
lot6.append(driver.find_elements_by_xpath('//td')[4].text)
lot6.append(driver.find_elements_by_xpath('//td')[5].text)
lot6.append(driver.find_elements_by_xpath('//td')[6].text)
#lot6.append('--')
lot6.append(driver.find_elements_by_xpath('//td')[7].text)
#lot6.append('(--)')
print(lot6)
driver.get('https://www.mizuhobank.co.jp/retail/takarakuji/check/loto/loto7/index.html')
sleep(3)
lot7 = ['LOT7']
lot7.append(driver.find_elements_by_xpath('//th')[1].text)
lot7.append(driver.find_elements_by_xpath('//td')[0].text)
lot7.append(driver.find_elements_by_xpath('//td')[1].text)
lot7.append(driver.find_elements_by_xpath('//td')[2].text)
lot7.append(driver.find_elements_by_xpath('//td')[3].text)
lot7.append(driver.find_elements_by_xpath('//td')[4].text)
lot7.append(driver.find_elements_by_xpath('//td')[5].text)
lot7.append(driver.find_elements_by_xpath('//td')[6].text)
lot7.append(driver.find_elements_by_xpath('//td')[7].text)
lot7.append(driver.find_elements_by_xpath('//td')[8].text)
lot7.append(driver.find_elements_by_xpath('//td')[9].text)
print(lot7)
driver.get('https://www.mizuhobank.co.jp/retail/takarakuji/check/loto/miniloto/index.html')
sleep(3)
mini = ['MINI']
mini.append(driver.find_elements_by_xpath('//th')[1].text)
mini.append(driver.find_elements_by_xpath('//td')[0].text)
mini.append(driver.find_elements_by_xpath('//td')[1].text)
mini.append(driver.find_elements_by_xpath('//td')[2].text)
mini.append(driver.find_elements_by_xpath('//td')[3].text)
mini.append(driver.find_elements_by_xpath('//td')[4].text)
mini.append(driver.find_elements_by_xpath('//td')[5].text)
#mini.append('--')
#mini.append('--')
mini.append(driver.find_elements_by_xpath('//td')[6].text)
#mini.append('(--)')
print(mini)
driver.close()

import csv

with open('getlotnumber.csv', 'w', newline='') as lot_file:
    writer = csv.writer(lot_file)
    writer.writerow(lot6)
    writer.writerow(lot7)
    writer.writerow(mini)
